name: PHPUnit

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

permissions:
  contents: read

jobs:

  tests:
    name: Tests

    env:
      extensions: curl,mbstring

    strategy:
      matrix:
        php:
          - '7.1'
          - '8.1'
        psr7:
          - guzzlehttp/psr7
          - laminas/laminas-diactoros
          - nyholm/psr7
          - slim/psr7
        client:
          - php-http/curl-client
          - symfony/http-client
        include:
          - php: '8.1'
            client: php-http/guzzle7-adapter
            psr7: guzzlehttp/psr7
          - php: '7.1'
            client: php-http/guzzle6-adapter
            psr7: guzzlehttp/psr7
          - php: '8.1'
            client: php-http/react-adapter
            psr7: nyholm/psr7
          - php: '7.1'
            client: php-http/react-adapter
            psr7: nyholm/psr7
      fail-fast: false

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          ini-values: date.timezone=Europe/Paris,memory_limit=-1,default_socket_timeout=10,session.gc_probability=0,zend.assertions=1
          php-version: "${{ matrix.php }}"
          extensions: "${{ env.extensions }}"

      - name: Install dependencies
        run: |
          echo "::group::composer update"
          composer require --ansi --no-update guzzlehttp/promises php-http/message-factory ${{ matrix.psr7 }} ${{ matrix.client }}
          composer update --ansi
          echo "::endgroup::"

          echo "::group::install phpunit"
          ./vendor/bin/simple-phpunit install
          echo "::endgroup::"

      - name: Run tests
        run: |
          ./vendor/bin/simple-phpunit
