name: PHPUnit

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

permissions:
  contents: read

jobs:

  tests:
    name: Tests

    strategy:
      matrix:
        php:
          - '7.2'
          - '8.1'
        psr7:
          - guzzlehttp/psr7
          - laminas/laminas-diactoros
          - nyholm/psr7
          - slim/psr7
        client:
          - php-http/curl-client
          - symfony/http-client
        include:
          - php: '8.1'
            client: php-http/guzzle7-adapter
            psr7: guzzlehttp/psr7
          - php: '7.2'
            client: php-http/guzzle6-adapter
            psr7: guzzlehttp/psr7:^1.9
          - php: '8.1'
            client: php-http/react-adapter
            psr7: nyholm/psr7
          - php: '7.2'
            client: php-http/react-adapter
            psr7: nyholm/psr7
          - php: '7.2'
            client: symfony/http-client
            psr7: phalcon
      fail-fast: false

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          ini-values: date.timezone=Europe/Paris,memory_limit=-1,default_socket_timeout=10,session.gc_probability=0,zend.assertions=1
          php-version: "${{ matrix.php }}"
          extensions: "curl,mbstring${{ matrix.psr7 == 'phalcon' && ',psr-1.1.0,phalcon-4.0.6' }}"

      - name: Install dependencies
        run: |
          echo "::group::composer update"
          if [ '${{ matrix.psr7 }}' = 'phalcon' ]; then
            composer require --ansi --no-update guzzlehttp/promises php-http/message-factory ${{ matrix.client }}
          else
            composer remove --ansi --no-update --dev nyholm/psr7
            composer require --ansi --no-update guzzlehttp/promises php-http/message-factory ${{ matrix.client }} ${{ matrix.psr7 }}
          fi
          composer update --ansi
          echo "::endgroup::"

          echo "::group::install phpunit"
          ./vendor/bin/simple-phpunit install
          echo "::endgroup::"

      - name: Run tests
        run: |
          ./vendor/bin/simple-phpunit
